# Generated by Django 4.2.16 on 2026-05-29 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP-адрес')),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Заблокирован')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('reason', models.CharField(choices=[('unique_url_limit', 'Превышен лимит уникальных URL'), ('error_rate_limit', 'Превышена доля ошибок 404'), ('rps_limit', 'Превышен лимит запросов в секунду'), ('manual', 'Ручная блокировка'), ('whitelist_violation', 'Нарушение whitelist')], default='unique_url_limit', max_length=50, verbose_name='Причина')),
                ('unique_urls_count', models.IntegerField(default=0, verbose_name='Уникальных URL')),
                ('total_requests', models.IntegerField(default=0, verbose_name='Всего запросов')),
                ('error_404_count', models.IntegerField(default=0, verbose_name='Ошибок 404')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Заблокированный IP',
                'verbose_name_plural': 'Заблокированные IP',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_or_subnet', models.CharField(max_length=50, unique=True, verbose_name='IP или подсеть')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлен')),
            ],
            options={
                'verbose_name': 'Доверенный IP',
                'verbose_name_plural': 'Доверенные IP',
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
                ('event_type', models.CharField(choices=[('blocked_request', 'Заблокированный запрос'), ('ip_blocked', 'IP заблокирован'), ('ip_unblocked', 'IP разблокирован'), ('threshold_warning', 'Предупреждение о пороге'), ('attack_detected', 'Обнаружена атака'), ('scan_detected', 'Обнаружено сканирование'), ('allowed_request', 'Разрешённый запрос')], max_length=30, verbose_name='Тип события')),
                ('source_ip', models.GenericIPAddressField(verbose_name='IP источника')),
                ('url', models.TextField(verbose_name='URL')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='Метод')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Код ответа')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('unique_urls_at_time', models.IntegerField(default=0, verbose_name='Уник. URL на момент события')),
                ('requests_in_window', models.IntegerField(default=0, verbose_name='Запросов в окне')),
                ('error_rate', models.FloatField(default=0.0, verbose_name='Доля ошибок')),
                ('details', models.JSONField(default=dict, verbose_name='Детали')),
            ],
            options={
                'verbose_name': 'Событие безопасности',
                'verbose_name_plural': 'События безопасности',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['source_ip'], name='waf_securit_source__a3fd39_idx'), models.Index(fields=['timestamp'], name='waf_securit_timesta_090b6e_idx'), models.Index(fields=['event_type'], name='waf_securit_event_t_10a99d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
                ('source_ip', models.GenericIPAddressField(verbose_name='IP источника')),
                ('method', models.CharField(max_length=10, verbose_name='Метод')),
                ('url', models.TextField(verbose_name='URL')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Код ответа')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('was_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('response_time_ms', models.FloatField(blank=True, null=True, verbose_name='Время ответа (мс)')),
            ],
            options={
                'verbose_name': 'Лог запроса',
                'verbose_name_plural': 'Лог запросов',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['source_ip'], name='waf_request_source__e9ccf1_idx'), models.Index(fields=['timestamp'], name='waf_request_timesta_de647e_idx'), models.Index(fields=['was_blocked'], name='waf_request_was_blo_bc99ec_idx')],
            },
        ),
    ]
